/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/d7dbpbnrQp6
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from "@/components/ui/card";


export function Component() {
  return (
    <div className="flex flex-col min-h-[100dvh]">
      {/* <Header /> */}
      
        {/* <section className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Your Preliminary Diagnosis
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Based on the symptoms and images you provided, our experts
                  have generated a preliminary diagnosis for your condition.
                </p>
              </div>
              <Card className="w-full max-w-md">
                <CardHeader>
                  <CardTitle>Preliminary Diagnosis</CardTitle>
                  <CardDescription>Acne Vulgaris</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    <p>
                      The symptoms and images you provided suggest that you may
                      be experiencing Acne Vulgaris. This is a common skin
                      condition characterized by pimples, blackheads, and other
                      blemishes.
                    </p>
                    <p>
                      We recommend scheduling an appointment with a
                      dermatologist for a full evaluation and treatment plan.
                      They will be able to provide a more accurate diagnosis and
                      recommend the appropriate treatment options.
                    </p>
                  </div>
                </CardContent>
                <CardFooter>
                  <Link
                    href="#"
                    className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-8 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    prefetch={false}
                  >
                    Find a Dermatologist
                  </Link>
                </CardFooter>
              </Card>
            </div>
          </div>
        </section> */}
      
      {/* <Footer /> */}
    </div>
  );
}

function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
